In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/ratings.csv")

df.head()

   0470536454   AXHY24HWOF184  5.0  1092009600
0  0470536454  A29OWR79AM796H  4.0  1491436800
1  0470536454   AUPWU27A7X5F6  5.0  1489449600
2  0470536454  A1N69A47D4JO6K  4.0  1487030400
3  0470536454   AHTIQUMVCGBFJ  5.0  1485648000
4  0470536454  A1J8LQ7HVLR9GU  5.0  1483488000

In [4]:
df.columns

Index(['0470536454', 'AXHY24HWOF184', '5.0', '1092009600'], dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1512529 entries, 0 to 1512528
Data columns (total 4 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   0470536454     1512529 non-null  str
 1   AXHY24HWOF184  1512529 non-null  str
 2   5.0            1512529 non-null  float64
 3   1092009600     1512529 non-null  int64
dtypes: float64(1), int64(1), str(2)
memory usage: 46.2 MB

In [6]:
import pandas as pd

cols = ["product_id", "user_id", "rating", "timestamp"]

df = pd.read_csv(
    "../data/ratings.csv",
    names=cols
)

df.head()

   product_id         user_id  rating   timestamp
0  0470536454   AXHY24HWOF184     5.0  1092009600
1  0470536454  A29OWR79AM796H     4.0  1491436800
2  0470536454   AUPWU27A7X5F6     5.0  1489449600
3  0470536454  A1N69A47D4JO6K     4.0  1487030400
4  0470536454   AHTIQUMVCGBFJ     5.0  1485648000

In [7]:
df = df.sample(n=150000, random_state=42)

In [8]:
df.shape

(150000, 4)

In [9]:
df.isnull().sum()

product_id    0
user_id       0
rating        0
timestamp     0
dtype: int64

In [10]:
df["rating"].value_counts()

rating
5.0    97633
4.0    23332
1.0    11818
3.0    10638
2.0     6579
Name: count, dtype: int64

In [11]:
df["user_id"].nunique()

132823

In [12]:
df["product_id"].nunique()

38626

In [13]:
df.to_csv("../data/cleaned_ratings.csv", index=False)