In [2]:
import pandas as pd

df = pd.read_csv("../data/cleaned_ratings.csv")

df.head()

   product_id         user_id  rating   timestamp
0  B005DBEAM0   A4V3MZPLN3XUU     2.0  1454112000
1  B01EA91TI8  A1VBE1QPSGE86B     4.0  1499990400
2  B004XNK7AI   A1HFCJ8R77PL2     5.0  1434499200
3  B001XJBWXG  A1D9FXN98XXFR9     3.0  1389398400
4  B012TAWYHU  A2M2RYPLQKJX3R     4.0  1469232000

In [3]:
popular = df.groupby("product_id")["rating"].mean()
popular = popular.sort_values(ascending=False)

popular.head(10)

product_id
0739084542    5.0
B01HJDJ1PA    5.0
B01HGDBHH8    5.0
B01HG9ROU6    5.0
B01HG7DDC6    5.0
B01HG6DWZU    5.0
B01HG293XO    5.0
B01HG0UMEU    5.0
B01HFN451O    5.0
B01HFFIFUE    5.0
Name: rating, dtype: float64

In [4]:
count = df.groupby("product_id")["rating"].count()

popular_df = pd.DataFrame({
    "avg_rating": popular,
    "num_reviews": count
})

popular_df = popular_df.sort_values(
    by=["avg_rating", "num_reviews"],
    ascending=False
)

popular_df.head(10)

            avg_rating  num_reviews
product_id
B003FO6E6M         5.0           20
B0064CF56C         5.0           19
B0006OHVMK         5.0           17
B0002D0DCA         5.0           16
B0002GJ4AY         5.0           16
B000PR3JEM         5.0           16
B000S91BI8         5.0           16
B0002D0DXE         5.0           15
B000U0DU34         5.0           15
B0113D2QUO         5.0           15

In [6]:
user_counts = df["user_id"].value_counts()

active_users = user_counts[user_counts > 20].index

df_small = df[df["user_id"].isin(active_users)]

df_small.shape

(117, 4)

In [7]:
product_counts = df_small["product_id"].value_counts()

popular_products = product_counts[product_counts > 20].index

df_small = df_small[df_small["product_id"].isin(popular_products)]

df_small.shape

(0, 4)

In [8]:
user_item = df_small.pivot_table(
    index="user_id",
    columns="product_id",
    values="rating"
)

In [9]:
user_item.shape

(0, 0)

In [10]:
user_item_filled = user_item.fillna(0)

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(user_item_filled)

ValueError: Found array with 0 sample(s) (shape=(0, 0)) while a minimum of 1 is required by check_pairwise_arrays.